### ISSUE TITLE
Reported Open/Closed Issues Have Been Deleted

### ISSUE THREAD

**Issue by borland1** [tronxy3d/F103_PIC480x320#1]
No History of Open and Closed Issues Exists after Repository was deleted.  This new repository lacks any reported history but appears the same as one that was deleted without explaination.

Normal housekeeping, is to start a new Branch.   What was done that, or what is my mis-understanding about this issue?

**Comment by tronxy3d** [comment]
We apologize for deleting the original repository during the update. This update has solved some problems encountered before:

1. The temperature is not displayed on the Filament interface

2. Some problems that the touch screen cannot click

**Comment by tronxy3d** [comment]
We apologize for deleting the original repository during the update. This update has solved some problems encountered before:
1.The temperature is not displayed on the Filament interface
2.Some problems that the touch screen cannot click
3.Other problems
If you have some problems using this firmware before, you can download the new firmware again and test it to see if it has been solved

**Comment by borland1** [comment]
Thanks for the reply and technical support.

That's great news that you are supporting the customers that bought earlier printer models.

Unfortunately, by not fully supporting **Open Source**, which typically includes historically documenting specific changes and associated code, you are making it difficult for many Tronxy customers to evaluate which features on which models are being updated with firmware bug fixes or improvements.

Also, you are making it the responsibility of the customer, to recompile, upload, and provide testing, to see if the latest firmware  working and worth doing.  Not everyone will have time or be encouraged to provide feedback of test results and make associated firmware update recommendations.

Hope you understand.
